#
# YAML file configuring the actions to take when releasing to production
#
# > Syntax tips here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Updating the data

on: 
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug
  schedule:
    - cron: '25 5 5 * *'

jobs:
  build-and-run-updating:
    name: Discover new sources

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    concurrency:
      group: ${{ github.workflow }}-updating
      cancel-in-progress: true   

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create UV installation"
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.28"

      - name: Running the script
        run: uv run maintenance/screen_linked_resources.py
                
      - name: Defining Git identity
        run: |
          git config user.name github_actions
          git config user.email github_actions@pierrevf.com

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "index-update/${{ github.run_id }}"
          base: "main"
          title: "Updating index"
